add pub key check

diff --git a/_gitolite_add_user b/_gitolite_add_user
--- a/_gitolite_add_user
+++ b/_gitolite_add_user
@@ -13,6 +13,9 @@ keypath=$2
 #check input params
 if [ -z $user ] || [ -z $keypath ]; then printf "\n  Usage: $0 gitolite add user <name> <keypath>\n\n"; exit -1; fi
 if [ ! -e $keypath ]; then echo "ERROR: file '$keypath' does not exists"; exit; fi
+ssh-keygen -l -f $keypath > /dev/null
+if [ ! $? -eq 0 ]; then echo "ERROR: file '$keypath' is not a public key file"; exit; fi
+
 
 #get git user name
 git_user=$(get_git_user_name)
